### ISSUE TITLE
Вторая итерация

### ISSUE THREAD

**Issue by valboldakov** [nongi3/olymp_sibsutis#2]
## Первостепенные задачи:

- [ ] перевести хранение информации на сервер (или хотя бы локально);
- [x] добавить список лотов.

## Второстепенные задачи:

- [ ] функционал получения баланса (текущего количества баллов);
- [ ] функционал перевода поинтов другому участнику;
- [ ] функционал ставок на лоты.
